# Generated by Django 4.2.4 on 2024-11-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0003_player_user_role'),
        ('accounts', '0009_organization_role_staff_role'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='form_image/'),
        ),
        migrations.AddField(
            model_name='form',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='form',
            name='termsandconditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='input_add_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='organisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='player_list',
            field=models.ManyToManyField(related_name='player_list', to='player_app.player'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_image/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short_answer', 'Short Answer'), ('paragraph', 'Paragraph'), ('multiple_choice', 'Multiple Choice'), ('multiple_choice_grid', 'Multiple Choice Grid'), ('checkbox', 'Check Boxes'), ('dropdown', 'Dropdowns'), ('file_upload', 'File Upload'), ('date', 'Date'), ('time', 'Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='related_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player_app.player'),
        ),
    ]
