# Generated by Django 4.2.4 on 2024-11-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0003_player_user_role'),
        ('form', '0002_form_isdelete_form_image_form_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='player_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='player_list', to='player_app.player'),
        ),
    ]
