# Generated by Django 4.2.4 on 2024-11-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_question_player_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
