# Generated by Django 4.2.4 on 2024-11-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_form_form_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_visibility',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=100),
        ),
    ]
