# Generated by Django 4.2.4 on 2024-11-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_form_form_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_activity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('data_input', 'Data Input'), ('move_to_trash', 'Move To Trash'), ('deleted', 'Deleted'), ('input_deleted', 'Input Deleted'), ('input_updation', 'Input Updation')], max_length=200),
        ),
    ]
