# Generated by Django 5.0.3 on 2024-12-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_form_activity_action'),
        ('player_app', '0003_player_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='player_list',
            field=models.ManyToManyField(blank=True, related_name='player_list', to='player_app.player'),
        ),
    ]
