# Generated by Django 5.0.3 on 2024-12-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_dailywellnessform'),
        ('player_app', '0003_player_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessFormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.player_group')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.player')),
                ('wellness_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.dailywellnessform')),
            ],
        ),
    ]
