# Generated by Django 5.1.1 on 2025-01-13 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0012_camptournament_campparticipant_campactivity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campparticipant",
            name="camp",
        ),
        migrations.RemoveField(
            model_name="campparticipant",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="camptournament",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="camptournament",
            name="organization",
        ),
        migrations.DeleteModel(
            name="CampActivity",
        ),
        migrations.DeleteModel(
            name="CampParticipant",
        ),
        migrations.DeleteModel(
            name="CampTournament",
        ),
    ]
