# Generated by Django 4.2.4 on 2024-10-20 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_staff_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='images/default_profile.jpg', null=True, upload_to='images/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry'), ('Ladakh', 'Ladakh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('others', 'others')], max_length=40, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('batting_style', models.CharField(blank=True, max_length=100, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=100, null=True)),
                ('handedness', models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], max_length=1, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('sports_role', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('age_category', models.CharField(blank=True, choices=[('boys_under-15', 'Boys under 15'), ('boys_under-19', 'Boys under 19'), ('men_under-23', 'Men Under 23'), ('men_senior', 'Men Senior')], max_length=50, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('aadhar_card_upload', models.FileField(blank=True, null=True, upload_to='documents/aadhar/')),
                ('pan_card_upload', models.FileField(blank=True, null=True, upload_to='documents/pan/')),
                ('marksheets_upload', models.FileField(blank=True, null=True, upload_to='documents/marksheets/')),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Guardian', 'Guardian'), ('Other', 'Other')], max_length=20, null=True)),
                ('guardian_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, to='player_app.group')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
