# Generated by Django 5.0.3 on 2024-10-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Player_Group',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='groups',
            new_name='players_in_groups',
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
