# Generated by Django 5.2.1 on 2026-01-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('ST/RH', 'Strength / Rehab Session'), ('CD', 'Conditioning Session'), ('A-INJ', 'Absent due to Injury'), ('A-PR', 'Absent Due to Personal Reason'), ('R', 'Rest')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='player_app.camptournament')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='player_app.player')),
            ],
            options={
                'unique_together': {('player', 'camp', 'attendance_date')},
            },
        ),
    ]
