# Generated by Django 4.2.4 on 2024-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0002_rename_group_player_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_role',
            field=models.CharField(default='Player', max_length=20),
        ),
    ]
