# Generated by Django 5.1.1 on 2025-01-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_organization_role"),
        ("player_app", "0004_camptournament_campparticipant_campactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.organization",
            ),
        ),
    ]
