# Generated by Django 5.1.1 on 2025-01-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0005_alter_player_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camptournament",
            name="organization",
        ),
        migrations.AddField(
            model_name="camptournament",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="camp_participants", to="player_app.player"
            ),
        ),
        migrations.AlterField(
            model_name="campparticipant",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camp_participants",
                to="player_app.camptournament",
            ),
        ),
    ]
