# Generated by Django 5.0.3 on 2025-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0008_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
