# Generated by Django 5.0.3 on 2025-02-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_physio'),
        ('player_app', '0010_remove_injury_medical_documents_medicaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_notes', models.TextField()),
                ('recovery_time_weeks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='player_app.injury')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.physio')),
            ],
        ),
    ]
