# Generated by Django 5.0.3 on 2025-02-17 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_physio_organization_remove_physio_user_and_more'),
        ('player_app', '0011_treatmentrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentrecommendation',
            name='injury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_app.injury'),
        ),
        migrations.AlterField(
            model_name='treatmentrecommendation',
            name='physio',
            field=models.ForeignKey(limit_choices_to={'role': 'physio'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='treatmentrecommendation',
            name='recovery_time_weeks',
            field=models.IntegerField(),
        ),
    ]
