# Generated by Django 5.0.3 on 2025-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0012_alter_treatmentrecommendation_injury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='treatment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
