# Generated by Django 5.1.1 on 2025-02-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_delete_physio"),
        ("player_app", "0013_treatmentrecommendation_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="camptournament",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organization",
            ),
        ),
    ]
