# Generated by Django 5.1.1 on 2025-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_app", "0014_camptournament_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camptournament",
            name="participants",
            field=models.ManyToManyField(related_name="camps", to="player_app.player"),
        ),
        migrations.DeleteModel(
            name="CampParticipant",
        ),
    ]
