# Generated by Django 4.2.23 on 2025-07-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_staff_close_injuries_staff_create_injury_and_more'),
        ('player_app', '0015_alter_camptournament_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='body_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='cause_of_injury',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='expected_date_of_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='nature_of_injury',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_injuries', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='injury',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='injury',
            name='type_of_activity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='injury',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='injury',
            name='affected_body_part',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='injury',
            name='injury_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='injury',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='injury',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='InjuryActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='player_app.injury')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
