# Generated by Django 4.2.23 on 2025-07-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_staff_close_injuries_staff_create_injury_and_more'),
        ('player_app', '0016_injury_body_segment_injury_cause_of_injury_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_injuries', to='accounts.staff'),
        ),
    ]
