# Generated by Django 4.2.23 on 2025-07-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0017_alter_injury_reported_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-date', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='injury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='player_app.injury'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='view_option',
            field=models.CharField(blank=True, choices=[('profile', 'Only Profile'), ('injury_profile', 'Injury and Profile'), ('injury_only', 'Only Injury')], max_length=20, null=True),
        ),
    ]
