# Generated by Django 4.2.23 on 2025-07-30 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0020_playeractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('SL Lunge Calf Raises', 'SL Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3×6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phase', models.CharField(max_length=128)),
                ('trial1', models.FloatField()),
                ('trial2', models.FloatField()),
                ('best', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_app.player')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_app.test')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
