# Generated by Django 4.2.23 on 2025-07-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0022_testandresult_remove_testresult_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testandresult',
            name='best',
        ),
    ]
