# Generated by Django 5.2.1 on 2025-08-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_staff_role_alter_staff_staff_role'),
        ('player_app', '0023_remove_testandresult_best'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('boys_under-15', 'Boys under 15'), ('boys_under-19', 'Boys under 19'), ('men_under-23', 'Men Under 23'), ('men_senior', 'Men Senior')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.organization')),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to='player_app.player')),
                ('staff', models.ManyToManyField(blank=True, related_name='teams', to='accounts.staff')),
            ],
        ),
    ]
