# Generated by Django 5.2.1 on 2025-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0024_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
