# Generated by Django 5.2.1 on 2025-09-16 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0025_team_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoyo_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='reported_by_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='yoyo_level',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='testandresult',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='testandresult',
            name='phase',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testandresult',
            name='test',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('SL Lunge Calf Raises', 'SL Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3×6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores')], max_length=32, null=True),
        ),
    ]
