# Generated by Django 5.2.1 on 2025-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0026_testandresult_created_at_testandresult_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_level', models.CharField(max_length=50)),
                ('shuttle_no', models.IntegerField()),
                ('speed_kmh', models.FloatField()),
                ('speed_ms', models.FloatField()),
                ('level_time', models.CharField(max_length=20)),
                ('total_distance', models.FloatField()),
                ('approximately_vo2max', models.FloatField()),
                ('final_level', models.CharField(max_length=50)),
                ('gender_m', models.CharField(max_length=10)),
                ('gender_f', models.CharField(max_length=10)),
                ('rating_f', models.CharField(max_length=50)),
                ('rating_m', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
