# Generated by Django 5.2.1 on 2025-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0027_nomativedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomativedata',
            name='approximately_vo2max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='final_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='gender_f',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='gender_m',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='level_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='rating_f',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='rating_m',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='shuttle_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='speed_kmh',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='speed_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='speed_ms',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='total_distance',
            field=models.FloatField(null=True),
        ),
    ]
