# Generated by Django 5.2.1 on 2025-09-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0028_alter_nomativedata_approximately_vo2max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomativedata',
            name='speed_level',
            field=models.IntegerField(null=True),
        ),
    ]
