# Generated by Django 5.2.1 on 2025-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0029_alter_nomativedata_speed_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomativedata',
            name='gender_f',
            field=models.CharField(default='Female', max_length=10),
        ),
        migrations.AlterField(
            model_name='nomativedata',
            name='gender_m',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
