# Generated by Django 5.2.1 on 2025-09-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0030_alter_nomativedata_gender_f_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testandresult',
            old_name='yoyo_level',
            new_name='final_level',
        ),
    ]
