# Generated by Django 5.2.1 on 2025-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0031_rename_yoyo_level_testandresult_final_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='target',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
