# Generated by Django 5.2.1 on 2025-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0032_testandresult_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='distance_covered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='predicted_vo2max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
