# Generated by Django 5.2.1 on 2025-09-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0033_testandresult_distance_covered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testandresult',
            options={},
        ),
        migrations.RenameField(
            model_name='testandresult',
            old_name='final_level',
            new_name='best',
        ),
        migrations.RemoveField(
            model_name='testandresult',
            name='trial',
        ),
    ]
