# Generated by Django 5.2.1 on 2025-09-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0034_alter_testandresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testandresult',
            name='best',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
