# Generated by Django 5.2.1 on 2025-09-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0035_alter_testandresult_best'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('test', models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('SL Lunge Calf Raises', 'SL Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3×6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores')], max_length=32)),
                ('average', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('test', models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('SL Lunge Calf Raises', 'SL Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3×6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores')], max_length=32)),
                ('average', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='testandresult',
            name='indv_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('SL Lunge Calf Raises', 'SL Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3×6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores')], max_length=32)),
                ('individual_average', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_app.player')),
            ],
        ),
    ]
