# Generated by Django 5.2.1 on 2025-09-26 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0036_categoryaggregate_genderaggregate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_max_formula', models.CharField(choices=[('all_players', 'All Players'), ('all_players_by_gender', 'All Players by Gender'), ('category_based', 'Category-based'), ('date_based', 'Date-based (dynamic)'), ('manual_entry', 'Manual Entry')], default='all_players', max_length=30)),
                ('min_is_better', models.BooleanField(default=False)),
                ('indv_avg_option', models.CharField(choices=[('total_result', 'Total Result'), ('date_based', 'Date Based')], default='total_result', max_length=20)),
                ('grp_avg_option', models.CharField(choices=[('all_players_date', 'Average All Players in Date Range'), ('all_players_gender_date', 'Average by Gender in Date Range'), ('category_based_date', 'Average by Category in Date Range'), ('all_players_stored', 'Average All Players Stored'), ('gender_stored', 'Average by Gender Stored'), ('category_stored', 'Average by Category Stored')], default='all_players_date', max_length=30)),
                ('categories', models.ManyToManyField(through='player_app.CategoryTarget', to='player_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='categorytarget',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_targets', to='player_app.reportsettings'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytarget',
            unique_together={('settings', 'category')},
        ),
    ]
