# Generated by Django 5.2.1 on 2025-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0038_alter_player_age_category_alter_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='body_segment',
        ),
        migrations.RemoveField(
            model_name='injury',
            name='injury_type',
        ),
        migrations.AddField(
            model_name='injury',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='player_status',
            field=models.CharField(choices=[('full participation', 'full participation'), ('limited participation', 'limited participation'), ('no\xa0participation', 'no\xa0participation')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='unknown_injury_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='grp_avg_option',
            field=models.CharField(choices=[('all_players_date', 'Average All Players in Date Range'), ('all_players_gender_date', 'Average by Gender in Date Range'), ('all_players_stored', 'Average All Players Stored'), ('gender_stored', 'Average by Gender Stored'), ('category_stored', 'Average by Category Stored')], default='all_players_date', max_length=30),
        ),
    ]
