# Generated by Django 5.2.1 on 2025-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0039_remove_injury_body_segment_remove_injury_injury_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='player_status',
            field=models.CharField(choices=[('full participation', 'Full Participation'), ('limited participation', 'Limited Participation'), ('no participation', 'No Participation')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[(' Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicket-keeper', 'Wicket-keeper'), ('Wicket-keeper Batsman', 'Wicket-keeper Batsman')], max_length=100, null=True),
        ),
    ]
