# Generated by Django 5.2.1 on 2025-10-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0040_alter_injury_player_status_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_status',
            field=models.CharField(choices=[('full participation', 'Full Participation'), ('limited participation', 'Limited Participation'), ('no participation', 'No Participation')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('Batter', 'Batter'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicket-keeper', 'Wicket-keeper')], max_length=100, null=True),
        ),
    ]
