# Generated by Django 5.2.1 on 2025-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0041_player_player_status_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='diagnosis_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='severity_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='side',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='traning_participation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
