# Generated by Django 5.2.1 on 2025-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0042_injury_action_taken_injury_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camptournament',
            name='age_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camptournament',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
