# Generated by Django 5.2.1 on 2025-11-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0043_camptournament_age_category_camptournament_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testandresult',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.camptournament'),
        ),
    ]
