# Generated by Django 5.2.1 on 2025-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0044_alter_testandresult_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='run_a_3x6_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
