# Generated by Django 5.2.1 on 2025-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0045_testandresult_run_a_3x6_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='sl_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='slg_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
