# Generated by Django 5.2.1 on 2025-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0046_testandresult_sl_difference_testandresult_sl_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='sl_cr_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_cr_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_cr_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_cr_right',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
