# Generated by Django 5.2.1 on 2025-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0047_testandresult_sl_cr_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='mb_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='mb_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='mb_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='mb_right',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
