# Generated by Django 5.2.1 on 2025-12-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0048_testandresult_mb_difference_testandresult_mb_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='copenhagen_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='copenhagen_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='copenhagen_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='copenhagen_right',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
