# Generated by Django 5.2.1 on 2025-12-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0049_testandresult_copenhagen_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='sl_hop_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_hop_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_hop_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='sl_hop_right',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
