# Generated by Django 5.2.1 on 2025-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0050_testandresult_sl_hop_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='cmj_box_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_contract_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_flight_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_force',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_jump_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_jump_type',
            field=models.CharField(blank=True, choices=[('Countermovement Jump', 'Countermovement Jump'), ('Squat Jump', 'Squat Jump'), ('Drop Jump', 'Drop Jump')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_reactive_strength_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_readiness_color',
            field=models.CharField(blank=True, choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_stiffness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
