# Generated by Django 5.2.1 on 2025-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0051_testandresult_cmj_box_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testandresult',
            name='cmj_body_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='cmj_push_off_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
