# Generated by Django 5.2.1 on 2025-12-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0052_testandresult_cmj_body_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testandresult',
            old_name='cmj_contract_time',
            new_name='cmj_contact_time',
        ),
    ]
