# Generated by Django 5.2.1 on 2025-12-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0053_rename_cmj_contract_time_testandresult_cmj_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testandresult',
            name='cmj_jump_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testandresult',
            name='cmj_readiness_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
