# Generated by Django 5.2.1 on 2025-12-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0056_testandresult_dexa_bmd_testandresult_dexa_bmi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testandresult',
            name='dexa_total_lean',
        ),
    ]
