# Generated by Django 5.2.1 on 2025-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0058_testandresult_blood_albumin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
