# Generated by Django 5.2.1 on 2025-12-04 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0059_player_current_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySncLogCamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, null=True)),
                ('coach_name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('concerns', models.TextField(blank=True)),
                ('niggles', models.BooleanField(default=False)),
                ('recovery_sessions', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snc_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('team', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyActivityCamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=80)),
                ('duration', models.CharField(blank=True, choices=[('<1', '< 1 hr'), ('1-2', '1 - 2 hrs'), ('2-3', '2 - 3 hrs'), ('3-4', '3 - 4 hrs'), ('>4', '> 4 hrs')], max_length=10)),
                ('intensity', models.CharField(blank=True, choices=[('1', '1 - Very Low'), ('2', '2 - Low'), ('3', '3 - Moderate'), ('4', '4 - High'), ('5', '5 - Very High')], max_length=2)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='player_app.dailysnclogcamps')),
            ],
        ),
    ]
