# Generated by Django 5.2.1 on 2025-12-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0060_dailysnclogcamps_dailyactivitycamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysnclogcamps',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.camptournament'),
        ),
    ]
