# Generated by Django 5.2.1 on 2025-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0061_alter_dailysnclogcamps_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_category',
            field=models.CharField(blank=True, choices=[('boys_under-16', 'Boys under 16'), ('boys_under-19', 'Boys under 19'), ('men_under-23', 'Men Under 23'), ('men_senior', 'Men Senior'), ('girls_under-15', 'Girls under 15'), ('girls_under-19', 'Girls under 19'), ('women_under-23', 'Women Under 23'), ('women_senior', 'Women Senior')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('boys_under-16', 'Boys under 16'), ('boys_under-19', 'Boys under 19'), ('men_under-23', 'Men Under 23'), ('men_senior', 'Men Senior'), ('girls_under-15', 'Girls under 15'), ('girls_under-19', 'Girls under 19'), ('women_under-23', 'Women Under 23'), ('women_senior', 'Women Senior')], max_length=100, null=True),
        ),
    ]
