# Generated by Django 5.2.1 on 2025-12-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0062_alter_player_age_category_alter_team_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testandresult',
            old_name='run_a_3x6_attempts',
            new_name='run_a_3x6_attempt1',
        ),
        migrations.AddField(
            model_name='testandresult',
            name='run_a_3x6_attempt2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='run_a_3x6_attempt3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='run_a_3x6_attempt5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='run_a_3x6_attempt6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='run_a_3x6_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testandresult',
            name='run_a_3x6_average4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
