# Generated by Django 5.2.1 on 2025-12-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0063_rename_run_a_3x6_attempts_testandresult_run_a_3x6_attempt1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testandresult',
            old_name='run_a_3x6_average4',
            new_name='run_a_3x6_attempt4',
        ),
    ]
