# Generated by Django 5.2.1 on 2025-12-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0064_rename_run_a_3x6_average4_testandresult_run_a_3x6_attempt4'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='skill_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
