# Generated by Django 5.2.1 on 2025-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0065_injury_skill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='skill_status',
        ),
        migrations.AddField(
            model_name='player',
            name='skill_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='traning_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
