# Generated by Django 5.2.1 on 2025-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0066_remove_injury_skill_status_player_skill_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
