# Generated by Django 5.2.1 on 2025-12-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0068_categoryaggregate_left_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=64)),
                ('test', models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('SL Lunge Calf Raises', 'SL Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3x6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores'), ('Anthropometry Test', 'Anthropometry Test'), ('Blood Work', 'Blood Work'), ('DEXA Scan Test', 'DEXA Scan Test')], max_length=32)),
                ('average', models.FloatField(null=True)),
                ('left_min', models.FloatField(null=True)),
                ('left_max', models.FloatField(null=True)),
                ('right_min', models.FloatField(null=True)),
                ('right_max', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min', models.FloatField(null=True)),
                ('max', models.FloatField(null=True)),
            ],
        ),
    ]
