# Generated by Django 5.2.1 on 2025-12-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0070_alter_campaggregate_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='handedness',
            field=models.CharField(blank=True, choices=[('Right', 'Right'), ('Left', 'Left')], max_length=10, null=True),
        ),
    ]
