# Generated by Django 5.2.1 on 2025-12-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0071_alter_player_gender_alter_player_handedness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('blood_hemoglobin', models.FloatField(blank=True, null=True)),
                ('blood_rbc', models.FloatField(blank=True, null=True)),
                ('blood_platelets', models.FloatField(blank=True, null=True)),
                ('blood_albumin', models.FloatField(blank=True, null=True)),
                ('blood_globulin', models.FloatField(blank=True, null=True)),
                ('blood_uric_acid', models.FloatField(blank=True, null=True)),
                ('blood_creatinine', models.FloatField(blank=True, null=True)),
                ('blood_testosterone', models.FloatField(blank=True, null=True)),
                ('blood_iron', models.FloatField(blank=True, null=True)),
                ('blood_vitamin_d3', models.FloatField(blank=True, null=True)),
                ('blood_cholesterol', models.FloatField(blank=True, null=True)),
                ('blood_hdl', models.FloatField(blank=True, null=True)),
                ('blood_ldl', models.FloatField(blank=True, null=True)),
                ('blood_ldl_hdl_ratio', models.FloatField(blank=True, null=True)),
                ('blood_vitamin_b12', models.FloatField(blank=True, null=True)),
                ('blood_lipoprotein', models.FloatField(blank=True, null=True)),
                ('blood_homocysteine', models.FloatField(blank=True, null=True)),
                ('blood_protein', models.FloatField(blank=True, null=True)),
                ('blood_t3', models.FloatField(blank=True, null=True)),
                ('blood_t4', models.FloatField(blank=True, null=True)),
                ('blood_tsh', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_by_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.camptournament')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_app.player')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_tests_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
