# Generated by Django 5.2.1 on 2025-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0072_bloodtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='anterior_apprehension_left',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='anterior_apprehension_right',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='dominant_side',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='gird_erg_left',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='gird_erg_right',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='hk_test_left',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='hk_test_right',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='lead_leg',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='lld',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='mid_foot_left',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='mid_foot_right',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='obriens_left',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='obriens_right',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='participation_category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='rear_foot_left',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='rear_foot_right',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='relocation_left',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mskinjuryassessment',
            name='relocation_right',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
