# Generated by Django 5.2.1 on 2025-12-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0073_alter_mskinjuryassessment_anterior_apprehension_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaggregate',
            name='test',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('S/L Lunge Calf Raises', 'S/L Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3x6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores'), ('Anthropometry Test', 'Anthropometry Test'), ('Blood Work', 'Blood Work'), ('DEXA Scan Test', 'DEXA Scan Test'), ('MSK Injury Assessment', 'MSK Injury Assessment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='test',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('S/L Lunge Calf Raises', 'S/L Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3x6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores'), ('Anthropometry Test', 'Anthropometry Test'), ('Blood Work', 'Blood Work'), ('DEXA Scan Test', 'DEXA Scan Test'), ('MSK Injury Assessment', 'MSK Injury Assessment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='test',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('S/L Lunge Calf Raises', 'S/L Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3x6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores'), ('Anthropometry Test', 'Anthropometry Test'), ('Blood Work', 'Blood Work'), ('DEXA Scan Test', 'DEXA Scan Test'), ('MSK Injury Assessment', 'MSK Injury Assessment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='test',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('S/L Lunge Calf Raises', 'S/L Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3x6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores'), ('Anthropometry Test', 'Anthropometry Test'), ('Blood Work', 'Blood Work'), ('DEXA Scan Test', 'DEXA Scan Test'), ('MSK Injury Assessment', 'MSK Injury Assessment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='testandresult',
            name='test',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('40m', '40m'), ('YoYo', 'YoYo'), ('SBJ', 'SBJ'), ('S/L Glute Bridges', 'S/L Glute Bridges (Sec)'), ('S/L Lunge Calf Raises', 'S/L Lunge Calf Raises'), ('MB Rotational Throws', 'MB Rotational Throws'), ('Copenhagen', 'Copenhagen (Sec)'), ('S/L Hop', 'S/L Hop'), ('Run A 3', 'Run A 3'), ('Run A 3x6', 'Run A 3x6'), ('1 Mile', '1 Mile'), ('Push-ups', 'Push-ups'), ('2 KM', '2 KM'), ('CMJ Scores', 'CMJ Scores'), ('Anthropometry Test', 'Anthropometry Test'), ('Blood Work', 'Blood Work'), ('DEXA Scan Test', 'DEXA Scan Test'), ('MSK Injury Assessment', 'MSK Injury Assessment')], max_length=32, null=True),
        ),
    ]
