# Generated by Django 5.2.1 on 2025-12-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0075_rename_copenhagen_difference_copenhagentest_difference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWellnessTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('urine_color', models.CharField(choices=[('NO_COLOR', 'No Color'), ('PALE_STRAW', 'Pale Straw Yellow'), ('TRANSLUCENT_YELLOW', 'Translucent Yellow'), ('DARK_YELLOW', 'Dark Yellow'), ('AMBER', 'Amber'), ('BROWN', 'Brown')], max_length=32)),
                ('soreness_level', models.PositiveSmallIntegerField()),
                ('fatigue_level', models.PositiveSmallIntegerField()),
                ('sleep_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('has_pain', models.BooleanField()),
                ('pain_comment', models.TextField(blank=True)),
                ('motivation_level', models.PositiveSmallIntegerField()),
                ('balls_bowled', models.PositiveIntegerField()),
                ('training_session_types', models.JSONField(default=list)),
                ('total_rpe', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_wellness_tests', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellness_tests', to='player_app.camptournament')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellness_tests', to='player_app.player')),
            ],
            options={
                'verbose_name': 'Daily Wellness Test',
                'verbose_name_plural': 'Daily Wellness Tests',
            },
        ),
    ]
