# Generated by Django 5.2.1 on 2025-12-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0076_dailywellnesstest'),
    ]

    operations = [
        migrations.AddField(
            model_name='copenhagentest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mbrotationalthrows',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='slglutebridges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='slhoptest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sllungecalfraises',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
