# Generated by Django 5.2.1 on 2026-01-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0078_runa3x6test'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysnclogcamps',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='campaggregate',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaggregate',
            name='left_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaggregate',
            name='left_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaggregate',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaggregate',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaggregate',
            name='right_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaggregate',
            name='right_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='left_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='left_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='right_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryaggregate',
            name='right_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysnclogcamps',
            name='coach_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='left_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='left_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='right_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genderaggregate',
            name='right_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='individual_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='left_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='left_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='right_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playeraggregate',
            name='right_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
