# Generated by Django 5.2.1 on 2026-01-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0079_dailysnclogcamps_enddate_alter_campaggregate_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywellnesstest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
