# Generated by Django 5.2.1 on 2026-01-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0080_dailywellnesstest_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysnclogcamps',
            name='enddate',
        ),
    ]
