# Generated by Django 5.2.1 on 2026-01-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0081_remove_dailysnclogcamps_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysnclogcamps',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
