# Generated by Django 5.2.1 on 2026-01-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0082_dailysnclogcamps_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='camp_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='player_app.camptournament'),
        ),
    ]
