# Generated by Django 5.2.1 on 2026-01-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0083_injury_camp_tournament'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysnclogcamps',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='injury',
            name='cause_of_injury',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='injury',
            name='severity',
            field=models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10, null=True),
        ),
    ]
