# Generated by Django 5.2.1 on 2026-01-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0084_alter_dailysnclogcamps_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysnclogcamps',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.camptournament'),
        ),
    ]
