# Generated by Django 5.2.1 on 2026-01-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0085_alter_dailysnclogcamps_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysnclogcamps',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.camptournament'),
        ),
        migrations.AlterField(
            model_name='dailywellnesstest',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellness_tests', to='player_app.camptournament'),
        ),
    ]
