# Generated by Django 5.2.1 on 2026-01-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0086_alter_dailysnclogcamps_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywellnesstest',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellness_tests', to='player_app.camptournament'),
        ),
    ]
