# Generated by Django 5.2.1 on 2026-01-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0088_playerattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlerDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ball_bowlerd', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler_drills', to='player_app.camptournament')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler_drills', to='player_app.player')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'camp', 'date')},
            },
        ),
    ]
