# Generated by Django 5.2.1 on 2026-01-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0089_bowlerdrill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bowlerdrill',
            old_name='ball_bowlerd',
            new_name='no_balls',
        ),
    ]
