# Generated by Django 5.2.1 on 2026-02-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0090_rename_ball_bowlerd_bowlerdrill_no_balls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_category',
            field=models.CharField(blank=True, choices=[('boys_under_16', 'Boys under 16'), ('boys_under_19', 'Boys under 19'), ('men_under_23', 'Men Under 23'), ('men_senior', 'Men Senior'), ('girls_under_15', 'Girls under 15'), ('girls_under_19', 'Girls under 19'), ('women_under_23', 'Women Under 23'), ('women_senior', 'Women Senior')], max_length=50, null=True),
        ),
    ]
