# Generated by Django 5.2.1 on 2026-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_organization_image'),
        ('player_app', '0091_alter_player_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='camptournament',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='camps', to='accounts.staff'),
        ),
    ]
