# Generated by Django 5.2.1 on 2026-03-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0093_testactivitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testactivitylog',
            old_name='user',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='testactivitylog',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='testactivitylog',
            name='test_result',
        ),
        migrations.AddField(
            model_name='testactivitylog',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_activity_logs', to='player_app.player'),
        ),
        migrations.AlterField(
            model_name='testactivitylog',
            name='activity_type',
            field=models.CharField(blank=True, default='UPDATE', max_length=100, null=True),
        ),
    ]
