# Generated by Django 5.2.1 on 2026-03-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0094_rename_user_testactivitylog_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testactivitylog',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.camptournament'),
        ),
    ]
