# Generated by Django 5.2.1 on 2026-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0095_testactivitylog_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='campactivity',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, to='player_app.player'),
        ),
    ]
