# Generated by Django 5.2.1 on 2026-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_organization_image'),
        ('player_app', '0096_campactivity_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='campactivity',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.staff'),
        ),
    ]
