# Generated by Django 5.2.1 on 2026-03-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0097_campactivity_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('player_added', 'Player Added'), ('player_removed', 'Player Removed'), ('staff_added', 'Staff Added'), ('staff_removed', 'Staff Removed'), ('deleted', 'Deleted'), ('recovered', 'Recovered')], max_length=50),
        ),
    ]
