# Generated by Django 5.2.1 on 2026-03-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0098_alter_campactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryactivitylog',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.camptournament'),
        ),
    ]
