# Generated by Django 5.2.1 on 2026-03-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0099_injuryactivitylog_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryactivitylog',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.player'),
        ),
    ]
