# Generated by Django 5.2.1 on 2026-03-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0100_injuryactivitylog_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injuryactivitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='injuryactivitylog',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
