# Generated by Django 5.2.1 on 2026-01-28 06:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('OrganizationAdmin', 'Organization Admin'), ('Staff', 'Staff'), ('Player', 'Player')], default='SuperAdmin', max_length=20)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('role', models.CharField(default='OrganizationAdmin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('player_management', models.BooleanField(default=False)),
                ('injury_tracking', models.BooleanField(default=False)),
                ('create_injury', models.BooleanField(default=False)),
                ('view_injuries', models.BooleanField(default=False)),
                ('update_injury_status', models.BooleanField(default=False)),
                ('close_injuries', models.BooleanField(default=False)),
                ('add_form', models.BooleanField(default=False)),
                ('add_result', models.BooleanField(default=False)),
                ('view_result', models.BooleanField(default=False)),
                ('create_camps_tournaments', models.BooleanField(default=False)),
                ('view_camps_tournaments', models.BooleanField(default=False)),
                ('create_program', models.BooleanField(default=False)),
                ('assign_program', models.BooleanField(default=False)),
                ('view_programs', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('selector', 'Selector'), ('sc_coach', 'S&C Coach'), ('physio', 'Physio'), ('support_staff', 'Support Staff'), ('other_coach', 'Other Coach')], default='Staff', max_length=20, null=True)),
                ('staff_role', models.CharField(blank=True, choices=[('selector', 'Selector'), ('sc_coach', 'S&C Coach'), ('physio', 'Physio'), ('support_staff', 'Support Staff'), ('other_coach', 'Other Coach')], default='Staffs', max_length=20, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
