# Generated by Django 5.0.3 on 2024-10-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('OrganizationAdmin', 'Organization Admin'), ('Staff', 'Staff'), ('Player', 'Player')], default='Staff', max_length=20),
        ),
    ]
