# Generated by Django 5.0.3 on 2024-11-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
