# Generated by Django 5.0.3 on 2024-11-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_super_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='form_submit',
            new_name='add_form',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='input_submit',
            new_name='add_result',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='view_input',
            new_name='view_result',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
    ]
