# Generated by Django 5.0.3 on 2024-11-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_form_submit_staff_add_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('OrganizationAdmin', 'Organization Admin'), ('Staff', 'Staff'), ('Player', 'Player')], default='Super Admin', max_length=20),
        ),
    ]
