# Generated by Django 5.0.3 on 2024-11-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('OrganizationAdmin', 'Organization Admin'), ('Staff', 'Staff'), ('Player', 'Player')], default='Organization Admin', max_length=20),
        ),
    ]
