# Generated by Django 5.0.3 on 2024-11-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='role',
        ),
    ]
