# Generated by Django 5.0.3 on 2024-11-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_organization_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='role',
            field=models.CharField(default='Organization Admin', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(default='Staff', max_length=20),
        ),
    ]
