# Generated by Django 4.2.4 on 2024-11-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_role_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('OrganizationAdmin', 'Organization Admin'), ('Staff', 'Staff'), ('Player', 'Player')], default='SuperAdmin', max_length=20),
        ),
    ]
