# Generated by Django 5.0.3 on 2024-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(default='OrganizationAdmin', max_length=20),
        ),
    ]
