# Generated by Django 5.1.1 on 2025-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_organization_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="create_camps_tournaments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="view_camps_tournaments",
            field=models.BooleanField(default=False),
        ),
    ]
