# Generated by Django 5.1.1 on 2025-01-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_staff_create_camps_tournaments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="assign_program",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="create_program",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="view_programs",
            field=models.BooleanField(default=False),
        ),
    ]
