# Generated by Django 5.0.3 on 2025-02-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_staff_assign_program_staff_create_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physios', to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physio_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
