# Generated by Django 5.0.3 on 2025-02-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_physio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physio',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='physio',
            name='user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('selector', 'Selector'), ('sc_coach', 'S&C Coach'), ('physio', 'Physio'), ('support_staff', 'Support Staff'), ('other_coach', 'Other Coach')], default='Staff', max_length=20),
        ),
    ]
