# Generated by Django 5.0.3 on 2025-02-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_physio_organization_remove_physio_user_and_more'),
        ('player_app', '0012_alter_treatmentrecommendation_injury_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Physio',
        ),
    ]
