# Generated by Django 5.1.1 on 2025-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_delete_physio"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="close_injuries",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="create_injury",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="update_injury_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="view_injuries",
            field=models.BooleanField(default=False),
        ),
    ]
