# Generated by Django 4.2.23 on 2025-07-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_staff_close_injuries_staff_create_injury_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='roles',
        ),
    ]
