# Generated by Django 4.2.23 on 2025-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_role_staff_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='roles',
            new_name='role',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('selector', 'Selector'), ('sc_coach', 'S&C Coach'), ('physio', 'Physio'), ('support_staff', 'Support Staff'), ('other_coach', 'Other Coach')], default='Staffs', max_length=20),
        ),
    ]
