# Generated by Django 4.2.23 on 2025-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_roles_staff_role_staff_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('selector', 'Selector'), ('sc_coach', 'S&C Coach'), ('physio', 'Physio'), ('support_staff', 'Support Staff'), ('other_coach', 'Other Coach')], default='Staff', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('selector', 'Selector'), ('sc_coach', 'S&C Coach'), ('physio', 'Physio'), ('support_staff', 'Support Staff'), ('other_coach', 'Other Coach')], default='Staffs', max_length=20, null=True),
        ),
    ]
