# Generated by Django 5.2.1 on 2026-02-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
    ]
